name: Swift

on: [pull_request]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run SwiftLint
      run: |
        swiftlint
    - name: Pod lib lint
      run: |
        gem install cocoapods
        pod lib lint --allow-warnings
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
