name: Swift

on: [pull_request]

jobs:
  build:

    runs-on: macos

    steps:
    - uses: actions/checkout@v2
    - name: Install and run SwiftLint
      run: |
        brew install swiftlint
        swiftlint
    - name: Lint pod lib
      run: |
        gem install cocoapods
        pod lib lint
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
